### ISSUE TITLE
settings menu appears only once

### ISSUE THREAD

**Issue by schristiany** [krishkrush/PlayneVR#10]
sitting at the fireplace, I opened the settings menu to change video settings. After closing the settings, I didn't manage to open it again

VR Hardware: Valve Index

**Comment by VismayaStudio** [comment]
Thank you.

**Comment by schristiany** [comment]
I just playes around with this. To clarify, its the B-Button on left controller, which should open a menu (setting, quit to desktop...). I get this menu one time after starting the  game and one time after meditation. In both situation, as soon as I pressed once on "settings", and press on X for leaving settings, I won't get any reaction on B-Button again.
Looks like the meditation is resetting something which leads to the 2nd chance.

**Comment by VismayaStudio** [comment]
Interesting. Clearly the menu system is not working correctly. This is very useful, thanks for sharing.

**Comment by VismayaStudio** [comment]
Resolved.
