### ISSUE TITLE
auto detected graphics settings to high

### ISSUE THREAD

**Issue by schristiany** [krishkrush/PlayneVR#11]
the graphic auto detection set everything to "epic". The result were average FPS of 54
I reduced "AntiAliasing" and "PostProcessing" one step. I get stable 60 FPS now.

----------------
VR: Valve Index
CPU: AMD Ryzen 9 3900x
RAM: G.Skill DIMM 32 GB DDR4-3600 (CL16 16-16-36)
Graphics: Nvidia RTX 2070 Super

**Comment by VismayaStudio** [comment]
Great find. Totally overlooked this. Thank you.

**Comment by VismayaStudio** [comment]
The new build now benchmarks GPU settings appropriately for VR.
