### ISSUE TITLE
Replace Fox Tutorial recommending to hit spacebar/mouse button to a button on the VR remote

### ISSUE THREAD

**Issue by ChampAmos** [krishkrush/PlayneVR#13]
**Describe the bug**
Tutorial by the fox still recommends clicking the mouse button or hitting spacebar when you notice a thought distracting you despite being in VR and unable to see the mouse and keyboard.

**To Reproduce**
During the tutorial 

**Expected behaviour**
I would expect me to recommend to use a button on the Oculus Touch Controller

**VR Hardware Used:**
Oculus Rift S

**Comment by schristiany** [comment]
the medidation guide gives  similar advice "press spacebar/mouse button for ringing attention bell"

**Comment by VismayaStudio** [comment]
Thank you.

**Comment by VismayaStudio** [comment]
Friends, I've added a specific dialogue branch for VR controls.
