### ISSUE TITLE
Changes in meditation menu take effect only after leaving to main menu

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#15]
Changes of settings in meditation menu take effect only after leaving to main menu and back, or shutting down game and starting it again.

**VR Hardware Used:** Valve Index

**Comment by VismayaStudio** [comment]
Thanks @Polix-cz for raising this.

Which settings did you change specifically?

**Comment by Polix-cz** [comment]
I changed all in upper row, and later different combinations, but I'm not sure if it all of them worked only after going to main menu. I didn't tried them one by one yet.

**Comment by Polix-cz** [comment]
I tried each option in meditation menu. All meditations settings ( No Warm-Up, No Guided Audio and  No Thoughts Sounds) work without problems. From Interface settings "No Text Guide?" doesn't work at all, text is missing only if I select "No Interface?". All other settings (No Interface?, No Breath Bubble?, Numeric Clock) take change only after leaving to main menu or game.
Also "Numeric Clock" switch is smaller and its sometimes hard to set it, others are better but still sometimes I need few tries to switch them.

**Comment by VismayaStudio** [comment]
Thanks @Polix-cz - I can confirm this issue.

**Comment by VismayaStudio** [comment]
Fixed.

This was a really good find! thank you!
