### ISSUE TITLE
Time resets to default after meditation

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#16]
**Describe the bug**
If time is changed in story mode before meditation(for example to evening), it resets to default after meditation is finished. Time go back to changed setting (evening) after meditation menu is reopen. If time is changed in story mode, after switching to sandbox mode and opening meditation menu, time change againg (to evening).

**To Reproduce**
start story mode
change time
meditate
reopen meditation menu
switch to sandbox mode
open meditation menu

**VR Hardware Used:** Valve Index

**Comment by VismayaStudio** [comment]
Thank you @Polix-cz — This will be fixed at a later date.
