### ISSUE TITLE
Talk to fox icon in main menu

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#17]
**Describe the bug**
White rhombus icon is sometimes present in main menu when fox wants to talk with you, but instead to be over fox's head
its about 10 cm in front your face.

**Screenshots**
![20201113155558_1_vr](https://user-images.githubusercontent.com/73604360/99906177-ed8c8e80-2cd5-11eb-900c-112c85a1c2a3.jpg)
![20201122135250_1_vr](https://user-images.githubusercontent.com/73604360/99906178-eebdbb80-2cd5-11eb-9d11-3f83826de4e4.jpg)

**VR Hardware Used:** Valve Index

**Comment by VismayaStudio** [comment]
Thank you @Polix-cz — this issues has now been resolved.
