### ISSUE TITLE
Sticks in evolve mode

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#18]
**Describe the bug**
Stick marking new seed is not set in the ground, but instead is floating horizontally above.

**To Reproduce**
plant tree in evolve mode

**Screenshots**
![20201122135411_1](https://user-images.githubusercontent.com/73604360/99906299-92a76700-2cd6-11eb-9d19-2178cf3b90b1.jpg)

**VR Hardware Used:** Valve Index

**Comment by VismayaStudio** [comment]
Confirmed. Thank you.

**Comment by VismayaStudio** [comment]
resolved.
