### ISSUE TITLE
Main Menu Options Hard to Read

### ISSUE THREAD

**Issue by Bronami** [krishkrush/PlayneVR#19]
**Describe the bug**
The main menu graphics can become unreadable with very gentle movement of the head. With the inability to teleport in the main menu, user is unable to get closer to read the smaller print of the options menu. This is most likely due to the transparency of the menu, as areas behind it such as the tree make the smearing far worse. As well, with a lack of highlight on the options, it can be difficult to know what is selected.

**To Reproduce**
Enter the main menu and select options, then sway head forward or side to side.

**Expected behavior**
The main menu should have crisp, easy-to-read font and colors that are independent of movement and position.

**Screenshots**
![main_menu_gfx](https://user-images.githubusercontent.com/10772328/101088190-49320400-3581-11eb-912f-94c489de0c7c.jpg)
![selection_difficulty](https://user-images.githubusercontent.com/10772328/101088198-4cc58b00-3581-11eb-8e40-531f9167c01d.jpg)

**VR Hardware Used:**
HTC Vive

**Comment by Polix-cz** [comment]
There seems to be problem with menu and reflective background, like water. It makes menu unreadable.
![20201203092858_1](https://user-images.githubusercontent.com/73604360/101143776-aaa4b200-3617-11eb-835d-46a05be8894f.jpg)
![20201204092635_1](https://user-images.githubusercontent.com/73604360/101143784-ac6e7580-3617-11eb-8b92-ae9108649a4b.jpg)
