### ISSUE TITLE
Teleporting to the Water and Being Unable to Return

### ISSUE THREAD

**Issue by Bronami** [krishkrush/PlayneVR#20]
**Describe the bug**
It is possible for the player to teleport away from the island, escaping to under the water and being unable to return. The player can still meditate, but will be unable to change position again without a restart.

**To Reproduce**
 This can be done by finding a teleport location that doesn't appear on the UI as a ground-arrow, but still has the light rope extending from the controller. It might take a few attempts, but teleporting out over and over towards the ocean in any area will eventually result in the player getting stuck at the ocean floor.

**Expected behavior**
Leaving the island should be blocked, or, in the least, a way to return to the island should be provided in a worst case scenario.

**Screenshots**
![serene](https://user-images.githubusercontent.com/10772328/101088671-06bcf700-3582-11eb-8126-3e24fdecc3f8.jpg)

**VR Hardware Used:**
HTC Vive

**Additional context**
Although the barrier took a few attempts to defeat, I was able to successfully escape the island and submerge myself in the water. I was unable to return to the island naturally, and it required a restart.

**Comment by VismayaStudio** [comment]
Resolved. :)
