### ISSUE TITLE
"Press A" Message Constantly Visible During Meditation

### ISSUE THREAD

**Issue by Bronami** [krishkrush/PlayneVR#21]
**Describe the bug**
During meditation, the "Press A to start meditation" dialogue will not go away, even after starting meditation. This warning still appears when the Vive controllers are being used. I had assumed that unplugging my Xbox controller would solve this issue, but this warning appears regardless of the controller being plugged in even after restart.

**To Reproduce**
Begin meditation, view left controller wrist to view message.

**Expected behavior**
Message should present Vive handset option, and disappear once meditation has started.

**Screenshots**
![press_a](https://user-images.githubusercontent.com/10772328/101089431-24d72700-3583-11eb-80af-5f5125875fa5.jpg)

**VR Hardware Used:**
HTC Vive

**Comment by VismayaStudio** [comment]
Resolved :)
