### ISSUE TITLE
[Minor] Graphical Artifacts

### ISSUE THREAD

**Issue by Bronami** [krishkrush/PlayneVR#22]
**Describe the bug**
On the main menu, there is a small square artifact that follows the rotation of the head.

There are strange lighting patterns around the campfire. Although not animated in the screenshot, Fox's back is flickering with a red light that does not seem to match that of the campfire nor the Achievement Obelisk. The pulsing light is at a different period than that of either light source.

**To Reproduce**
Look down at main menu, rotate head to view tracked square.

View ground or Fox near the campfire.

**Expected behavior**
Main menu floor should be free of extraneous elements.

Dynamic lighting near campfire should match that of visible light sources.

**Screenshots**
![main_menu_shape](https://user-images.githubusercontent.com/10772328/101090085-1d644d80-3584-11eb-9455-e4e42c1dece0.jpg)

![flicker](https://user-images.githubusercontent.com/10772328/101090523-c7dc7080-3584-11eb-96d1-5206fc6d8967.jpg)

**VR Hardware Used:**
HTC Vive

**Additional context**
These are both very minor graphical issues.

**Comment by VismayaStudio** [comment]
Thanks @Bronami - this should be resolved in the upcoming build
