### ISSUE TITLE
Achievements Not Visible

### ISSUE THREAD

**Issue by Bronami** [krishkrush/PlayneVR#23]
**Describe the bug**
When opening the Achievements menu using the Vive controller, the menu does not appear. Instead, a small green, glowing cylinder is produced at the center of the screen.

**To Reproduce**
Using the right Vive handset, look at the remote and press left on the touchpad to open the achievements menu. All other menus appear to work fine, but this menu will open as a green point of light.

**Expected behavior**
Achievements should appear like any other menu, or, if possible, it should simply display that the user has no achievements, if none are present yet.

**Screenshots**
![20201203155643_1](https://user-images.githubusercontent.com/10772328/101090694-0c680c00-3585-11eb-88ee-e584262c5b05.jpg)

**VR Hardware Used:**
HTC Vive

**Additional context**
This could be due to having no achievements at all, I am actually unsure if I have any. Although the cylinder appears in the right side of the screenshot, this is taken from the left eye's perspective, and is actually at the center of the screen.

**Comment by VismayaStudio** [comment]
Resolved :)
