### ISSUE TITLE
HTC Vive controller representation

### ISSUE THREAD

**Issue by RichardBTW** [krishkrush/PlayneVR#25]
Using HTC Vive with "donut on a stick" controllers. 

Playne was asking me to press A to continue - I don't have an A button.
When I pressed the grip button, the controller that shown in view was not a Vive controller.

**Comment by VismayaStudio** [comment]
RichardBTW, could you try going to settings > VR and choose VIVE there?

**Comment by RichardBTW** [comment]
Tried Playne VR again this evening, and now I can't get past the opening menu (with "Continue Story" at the top)

I know I have got beyond this before, but I can't remember how.

I have tried interacting using:
- Keyboard
- Mouse
- Xbox 360 controller
- Steam controller
- Vive controller(s)

Nothing would let me progress.

Sorry if I am being dense.
