### ISSUE TITLE
HTC Vive - Sound Output

### ISSUE THREAD

**Issue by RichardBTW** [krishkrush/PlayneVR#26]
When Playne was running, the game sound was coming out of the motherboard sound system (Realtek in my case) and not the Vive headphone output.

**Comment by VismayaStudio** [comment]
Hello RichardBTW, could you go to your SteamVR settings> Audio and share a screenshot of your settings there?

**Comment by RichardBTW** [comment]
![image](https://user-images.githubusercontent.com/63292825/102538286-048b8a00-40a4-11eb-9b41-52f9c9e00789.png)

**Comment by VismayaStudio** [comment]
Thanks Richard. 

Could you confirm if Playne VR was in focus when the audio was not working? You might have to click the Playne VR window on the desktop once it loads.

Thanks,

**Comment by RichardBTW** [comment]
I have just installed the new DLC version, and the sound works perfectly.
