### ISSUE TITLE
PlayneVR not registering as a VR app

### ISSUE THREAD

**Issue by gauravcm** [krishkrush/PlayneVR#27]
Describe the Bug:
I've successfully completed configuring PlayneVR to run from the Steam Library Properties>Beta menu as per the instructions provided.  When I launch PlayneVR from the pancake Steam app, I get the VR version running in my regular flatspace desktop only.  When I run SteamVR first and launch PlayneVR from there, PlayneVR is not recognized as a VR title and the VR Beta runs in the virtual theater mode as a regular flatspace title.

Expected Behaviour:
PlayneVR launches into headset cleanly as a native VR app.

VR Hardware Used: 
Oculus Rift S

**Comment by DunnoGuy** [comment]
The same for me:

In VR, the app just won't appear as a VR-app. Tried to verify files, switch from beta to stable and back from stable to beta - won't help.
The only way to run it is the VR-Theater, which is not an option though because controllers won't affect the app in this case =(

I'm using Oculus Quest 2



P.S. thank you for this amazing app and for maintaining and updating it so carefully!

**Comment by VismayaStudio** [comment]
Thanks guys. I am using a 'hacky' way to load the VR build onto the Playne Betas branch just now. 

Once I release VR, it'll be loaded using a different system on Steam and it should then hopefully work correctly. 

If you are having issues just drop me a DM on discord and I'll send you a key for the standalone build of Playne VR which should work.

**Comment by egglab2021** [comment]
Heya, I just wanted to report a very similar issue using the oculus quest 1 in rift/tethered mode.  If I try to start the VR version with the headset on it displays for a millisecond and then crashes, if i do with the headset off it starts in desktop theater mode, but neither the oculus controllers or the mouse/keyboard will let me interact with the menu.  I hope that's helpful, and thanks for putting the effort in for the VR port, it's appreciated!

**Comment by VismayaStudio** [comment]
Friends, you can now download Playne VR as a free DLC for Playne. Loading it via the DLC fixes the theatre mode issue.

Playne VR DLC : https://store.steampowered.com/app/1525880/Playne_VR/
