### ISSUE TITLE
Problem with talking to the Fox

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#28]
**Describe the bug**
In sandbox mode: It's not possible to talk to the Fox after selecting tree seeds and when you are near another tree. Instead of Fox menu, message about being too close to another tree to plant seed is shown.

In evolve mode: It's possible to talk to Fox after start, even close to tree, but not after planting tree. 

Another small issue with Fox, is menu tied to Fox, If you are standing on the side, too close or behind
the Fox, menu is not readable.

**To Reproduce**
In sandbox mode: Stand close to tree. Select tree seeds. Try to talk to the Fox.
In evolve mode: Plant tree. Try to talk to the Fox.

**Screenshots**
![20201213092418_1](https://user-images.githubusercontent.com/73604360/102007351-a15aca00-3d28-11eb-8883-3b1f3212987a.jpg)

**VR Hardware Used:** Valve Index

**Comment by VismayaStudio** [comment]
Resolved :) 

Seeing the back of the dialogue will be branched off to another issue.
