### ISSUE TITLE
Problems with seeds counter in evolve mode

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#29]
**Describe the bug**
HUD seeds counter in evolve mode shows 0 after start. After planting tree it starts showing correct number. When this counter shows 0, it's possible to talk to the Fox even close to a tree (issue #28)
Seed counter on right wrist shows correct number on start, but it's not updated after planting trees.

Under trees and seeds counters on right wrist is shown right thumbstick icon for selection of seeds, like in sandbox mode,
but there is nothing to select in evolve mode.

**VR Hardware Used:** Valve Index

**Comment by VismayaStudio** [comment]
Resolved :)
