### ISSUE TITLE
Problem with teleporting on Valve Index

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#30]
**Describe the bug**
When teleporting, after releasing thumbstick, direction in which you end facing after teleporing change. It doesn't happent always, but very offten. Change of direction is not constant, sometimes it's only few degrees off, very offten almost oposite direction.
Before version 0.6.0 teleporting worked without any issues.

**Screenshots**
![Playne-teleport-bug](https://user-images.githubusercontent.com/73604360/102494239-a5fae780-4074-11eb-9eb8-5412d0baccbd.gif)

**VR Hardware Used:**Valve Index

**Comment by VismayaStudio** [comment]
I've manged to improve this, although it isn't without it's quirks. Looking forward to finding out how the fix works for you.
