### ISSUE TITLE
Playne crashing on Windows 10 after end of meditation session

### ISSUE THREAD

**Issue by evtan** [krishkrush/PlayneVR#33]
**Describe the bug**
Playne is consistently crashing for me after the end of each meditation session. Even after repairing games files and reinstalling, the behaviour still persists. Error is "LowLevelFatalError".

**To Reproduce**
1. Start a meditation session.
2. At the end of the session, the game will crash.

**Expected behavior**
Meditation session should end and bring me back to the game campfire screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/25242533/102790655-bbf40980-43e0-11eb-934f-339891cd8c9b.png)

**VR Hardware Used:**
Not applicable.

**Additional context**
Crash behaviour only recently began, was working fine before.

**Comment by VismayaStudio** [comment]
Hello Evtan,

I presume that this is a bug related to the flat version of Playne and not VR? 

If so, there is a known bug where meditating in the 'emptiness' level crashes with this error message. Could you try meditating in another view and see if that works for you?

**Comment by evtan** [comment]
Thanks for clarifying! Yes I have been using the emptiness level recently. Okay will try that, thank you. Great game by the way it's been really helpful for my meditation practice.

**Comment by VismayaStudio** [comment]
Great! Let me know if you have any further issue Evtan. You can reach me on Playne's discord.

I'm closing this thread in the meantime since it does not relate to the VR build.
