### ISSUE TITLE
Stuck Underwater in Sandbox Mode

### ISSUE THREAD

**Issue by nrllewellyn** [krishkrush/PlayneVR#51]
**Describe the bug**
I used Playne in VR mode then returned to desktop mode. I am now stuck underwater (or possibly under the island?).

**To Reproduce**
Unknown. Possibly play game in  VR and then return to desktop mode?

**Expected behavior**
If outside the bounds of the island, auto-teleport back to the campfire. Or perhaps offer a "reset position" option in the menu

**Screenshots**
![20210129225318_1](https://user-images.githubusercontent.com/4811061/106346406-ec9f4c80-6284-11eb-9f88-ccce5fdcc5cb.jpg)

**VR Hardware Used:**
Valve Index

**Additional context**
None

**Comment by Polix-cz** [comment]
Same thing happened to me today, after switching from VR to flat version.

**Comment by KrishZilla** [comment]
Friends, thank you. This is now been resolved and patch will be released shortly. 

This issue is same as #41
