### ISSUE TITLE
Broken visuals in Evolve mode in VR

### ISSUE THREAD

**Issue by Polix-cz** [krishkrush/PlayneVR#53]
Evolve mode in VR is full of big pieces of grass or trees. Flat version and old beta VR 0.6.0 are not having this issue.

![20210129134803_1](https://user-images.githubusercontent.com/73604360/106385806-5d07b400-63d2-11eb-9f43-17174532c158.jpg)
![20210130143701_1](https://user-images.githubusercontent.com/73604360/106385809-5e38e100-63d2-11eb-927e-d61fe709eed4.jpg)

**Comment by KrishZilla** [comment]
Resolved :)
