### ISSUE TITLE
Teleporting buggy spots

### ISSUE THREAD

**Issue by Thorgram1974** [krishkrush/PlayneVR#6]
Certain spots around the waters edge and the stone monument have a below ground teleport target point. 

![vlcsnap-2020-10-28-21h59m54s873](https://user-images.githubusercontent.com/73623733/97516205-015c0380-1969-11eb-8b40-82c3ee776ed4.png)

Video in link shows example.
https://youtu.be/mgLPs0qDtgk

Headset used: Oculus Rift

**Comment by VismayaStudio** [comment]
Thank you so much! really helpful video as well.

**Comment by schristiany** [comment]
this happened to me too

**Comment by VismayaStudio** [comment]
Fixed
