### ISSUE TITLE
(valve index) Controls not working properly

### ISSUE THREAD

**Issue by schristiany** [krishkrush/PlayneVR#8]
at the selection screen, it is very hard to do a selection. The menu is too far away and it is hardly visible to see, if I'm on a topic. I needed several trigger presses to do the selection.

At the tutorial, the fox sits at the grass and is waiting for me. I have no pointer, found  no way to walk/teleport. I could move myself, but the fox  was behind my TV inside the wall ;)

used VR hardware:
Valve index

**Comment by VismayaStudio** [comment]
Thank you @schristiany

**Comment by schristiany** [comment]
I found out how it works:
- pressing trigger only works, if grip-button is not touched (hand must be completly opened)
- moving works with pressing left stick and moving stick into direction. I never had this bevore in any game. I sugest simply moving stick without pressing it.

**Comment by Polix-cz** [comment]
I lowered grip sensitivity and it fixed this problem.

**Comment by VismayaStudio** [comment]
Hello.

- Menu is now clearer.
- Teleport now happens by simply using the thumbstick without clicking it.

Could either of you confirm that the grip issue is still there? @Polix-cz is the issue there with the default grip sensitivity?

Thanks,
Krish.

**Comment by Polix-cz** [comment]
Yes, it's still very sensitive, slightest touch triggers grip. And that blocks trigger in menu, turning and selecting menu options with thumbstick.

**Comment by schristiany** [comment]
Hi,

sorry for late answer.
The Grip is still very sensitive during meditation.

Menu an teleport are perfect for me

Kind regards,
Stephan

**Comment by VismayaStudio** [comment]
Friends, the trigger for index now works correctly. This fix will be included for the build 0.7.1.1
